//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddMovieTryit.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMovie", ReplyAction="http://tempuri.org/IService1/AddMovieResponse")]
        string AddMovie(string Title, string Runtime, string Ratings, string Genre, string Director, string Studio, string Year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMovie", ReplyAction="http://tempuri.org/IService1/AddMovieResponse")]
        System.Threading.Tasks.Task<string> AddMovieAsync(string Title, string Runtime, string Ratings, string Genre, string Director, string Studio, string Year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AddMovieTryit.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AddMovieTryit.ServiceReference1.IService1>, AddMovieTryit.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddMovie(string Title, string Runtime, string Ratings, string Genre, string Director, string Studio, string Year) {
            return base.Channel.AddMovie(Title, Runtime, Ratings, Genre, Director, Studio, Year);
        }
        
        public System.Threading.Tasks.Task<string> AddMovieAsync(string Title, string Runtime, string Ratings, string Genre, string Director, string Studio, string Year) {
            return base.Channel.AddMovieAsync(Title, Runtime, Ratings, Genre, Director, Studio, Year);
        }
    }
}
